# snn

dem_autoencoder_segmentation.py

 image = image.reshape(4096,10)で実行↓
 
 
network.py  276行目でエラー発生
「index 10 is out of bounds for dimension 2 with size 10」
